POST http://localhost:3000/register
Content-Type: application/json

{
    "full_name": "John White",    
    "email": "john@email.com",
    "password": "secret123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "john@email.com",
    "password": "secret123"
}

###

POST http://localhost:3000/addgroup
Content-Type: application/json

{
    "name": "Trip to Paris"
   
}